### ISSUE TITLE
Use PHP WordPress Coding Standards?

### ISSUE THREAD

**Issue by maurobringolf** [WPSwitzerland/plugin-boilerplate-psr#1]
I personally like the idea of having a coding standard throughout a whole system and for a community project it would make a lot of sense, I think.

For reference: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Comment by markhowellsmead** [comment]
The WordPress coding standards conflict with the wider-ranging [PSR-2 standard](http://www.php-fig.org/psr/psr-2/). I'd prefer to adhere to the wider standard.

**Comment by grappler** [comment]
As we are writing code to be used within the WordPress ecosystem I personally believe we use the WordPress coding standards.

It would be good to create a travis setup to check the coding standards for future pull requests.

**Comment by markhowellsmead** [comment]
@grappler Re. Travis; can you go ahead and do that please? If we have to stick to the WordPress coding standards then I'll have to withdraw from taking part, as they conflict with PHP's own standards.

**Comment by markhowellsmead** [comment]
WordPress standard version at https://github.com/WPSwitzerland/plugin-boilerplate-wordpress.
